check:
  - thoth-build
  - thoth-precommit
  - thoth-pytest-py38
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
  build-stratergy: Source
  registry: quay.io
  registry-org: thoth-station
  registry-project: revsolver
  registry-secret: thoth-station-thoth-pusher-secret
deploy:
  project-org: "thoth-station"
  project-name: "thoth-application"
  image-name: "revsolver"
  overlay-contextpath: "revsolver/overlays/test/imagestreamtag.yaml"
